apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


images:
- name: ghcr.io/hanzoai/deploy
  newName: ghcr.io/hanzoai/deploy
  newTag: latest
resources:
- ./application-controller
- ./dex
- ./repo-server
- ./server
- ./config
- ./redis
- ./notification
- ./applicationset-controller
