apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../application-controller-roles
- hanzocd-application-controller-service.yaml
- hanzocd-application-controller-statefulset.yaml
- hanzocd-application-controller-deployment.yaml

