apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: notifications-controller
    app.kubernetes.io/name: hanzocd-notifications-controller
    app.kubernetes.io/part-of: hanzocd
  name: hanzocd-notifications-secret
type: Opaque
