apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: hanzocd-repo-server
    app.kubernetes.io/part-of: hanzocd
    app.kubernetes.io/component: repo-server
  name: hanzocd-repo-server
