apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- hanzocd-repo-server-sa.yaml
- hanzocd-repo-server-deployment.yaml
- hanzocd-repo-server-service.yaml
- hanzocd-repo-server-network-policy.yaml
