apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- hanzocd-application-controller-sa.yaml
- hanzocd-application-controller-role.yaml
- hanzocd-application-controller-rolebinding.yaml
