apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: hanzocd-commit-server
    app.kubernetes.io/part-of: hanzocd
    app.kubernetes.io/component: commit-server
  name: hanzocd-commit-server
