apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- hanzocd-commit-server-sa.yaml
- hanzocd-commit-server-deployment.yaml
- hanzocd-commit-server-service.yaml
- hanzocd-commit-server-network-policy.yaml

# Because commit-server is added as a resource outside the base, we have to explicitly set the image override here.
# If/when commit-server is added to the base, this can be removed.
images:
- name: ghcr.io/hanzoai/deploy
  newName: ghcr.io/hanzoai/deploy
  newTag: latest
