apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../application-controller-roles
- hanzocd-application-controller-statefulset.yaml
- hanzocd-metrics.yaml
- hanzocd-application-controller-network-policy.yaml