apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: hanzocd-dex-server
    app.kubernetes.io/part-of: hanzocd
    app.kubernetes.io/component: dex-server
  name: hanzocd-dex-server
