apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- hanzocd-dex-server-deployment.yaml
- hanzocd-dex-server-role.yaml
- hanzocd-dex-server-rolebinding.yaml
- hanzocd-dex-server-sa.yaml
- hanzocd-dex-server-service.yaml
- hanzocd-dex-server-network-policy.yaml