apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: hanzocd-redis
    app.kubernetes.io/part-of: hanzocd
  name: hanzocd-redis
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - hanzocd-redis
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create