apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- hanzocd-cm.yaml
- hanzocd-cmd-params-cm.yaml
- hanzocd-secret.yaml
- hanzocd-rbac-cm.yaml
- hanzocd-ssh-known-hosts-cm.yaml
- hanzocd-tls-certs-cm.yaml
- hanzocd-gpg-keys-cm.yaml

