apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- hanzocd-server-deployment.yaml
- hanzocd-server-role.yaml
- hanzocd-server-rolebinding.yaml
- hanzocd-server-sa.yaml
- hanzocd-server-service.yaml
- hanzocd-server-metrics.yaml
- hanzocd-server-network-policy.yaml