apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: hanzocd-applicationset-controller
    app.kubernetes.io/part-of: hanzocd
    app.kubernetes.io/component: applicationset-controller
  name: hanzocd-applicationset-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hanzocd-applicationset-controller
subjects:
  - kind: ServiceAccount
    name: hanzocd-applicationset-controller
