---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: hanzocd-applicationset-controller
    app.kubernetes.io/part-of: hanzocd
    app.kubernetes.io/component: applicationset-controller
  name: hanzocd-applicationset-controller