apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- hanzocd-applicationset-controller-rolebinding.yaml
- hanzocd-applicationset-controller-sa.yaml
- hanzocd-applicationset-controller-deployment.yaml
- hanzocd-applicationset-controller-role.yaml
- hanzocd-applicationset-controller-service.yaml
- hanzocd-applicationset-controller-network-policy.yaml
